server:
  port: 8080

spring:
  application:
    name: blog_system

  datasource:
    username: root
    password: mysqlrootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.115.220:3306/blog_system?serverTimezone=CTT&userUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 47.93.115.220
    port: 6379
    password: dc-redis

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      table-prefix: tb_
  type-aliases-package: com.hitenine.blog.pojo


sob.blog.image.save-path: D:\code\backend\images
# 2M
sob.blog.image.max-size: 2097152